qcmonge/webapp/mainapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('qcmonge/', include('qcmonge.urls')),
    path('admin/', admin.site.urls),
]

qcmonge/webapp/qcmonge/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from qcmonge.views import general, api, exportation, importation
from django.conf import settings

urlpatterns = [
    path('', general.index, name='index'),
    path('user/<str:user_login>', general.voir_user, name='voir-user'),
    path('themes/', general.voir_themes, name='voir-themes'),
        
    path('import/', importation.import_qcm, name='import1-qcm'),
    path('finalise-import/', importation.finalise_import_qcm, name='import2-qcm'),

    path('export/', exportation.export_qcm, name='export-qcm'),
    path('get-qcm-content/', exportation.get_qcm_content, name='get-qcm-content'),

    path('connect/', auth_views.LoginView.as_view(template_name='qcmonge/login.html'), name='login'),
    path('disconnect/', auth_views.LogoutView.as_view(template_name='qcmonge/login.html'), name='logout'),
    
    path('passwd/change/', auth_views.PasswordChangeView.as_view(template_name='qcmonge/change-pwd-do.html'), name='password_change'),
    path('passwd/change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='qcmonge/change-pwd-done.html'), name='password_change_done'),
    path('passwd/reset/', auth_views.PasswordResetView.as_view(template_name='qcmonge/reset-pwd-ask.html', extra_email_context={'site_name':settings.QCMONGE_SITE_NAME, 'domain':settings.QCMONGE_DOMAIN}), name='password_reset'),
    path('passwd/reset-sent/', auth_views.PasswordResetDoneView.as_view(template_name='qcmonge/reset-pwd-sent.html'), name='password_reset_done'),
    path('passwd/reset-do/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='qcmonge/reset-pwd-do.html'), name='password_reset_confirm'),
    path('passwd/reset-done/', auth_views.PasswordResetCompleteView.as_view(template_name='qcmonge/reset-pwd-done.html'), name='password_reset_complete'),

    path('api/structure/', api.api_structure, name='api-structure'),
    path('api/search-questions/', api.api_search_questions, name='api-search-questions'),
    path('api/infos-questions/', api.api_infos_questions, name='api-infos-questions'),
]

qcmonge/webapp/qcmonge/models/classement.py
from django.db import models


class Matiere(models.Model):
    intitule = models.CharField(max_length=30, primary_key=True, verbose_name='intitulé')

    class Meta:
        verbose_name = "matière"

        
    def __str__(self):
        return self.intitule


    
    
    
class Theme(models.Model):
    sujet = models.CharField(max_length=30, primary_key=True)
    domaine = models.ForeignKey(Matiere, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "thème"

        
    def __str__(self):
        return self.sujet + " (" + str(self.domaine) + ")"



    

class SousTheme(models.Model):
    motcle = models.CharField(max_length=30, primary_key=True, verbose_name='mot clé')
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "sous-thème"

        
    def __str__(self):
        return self.motcle + " (" + str(self.theme) + ")"

qcmonge/webapp/qcmonge/models/dependances.py
from django.db import models

from qcmonge.models.question import Question


class Fichier(models.Model):
    filename = models.CharField(max_length=100, primary_key=True)
    
    def __str__(self):
        return self.filename




class Filedep(models.Model):
    qid = models.ForeignKey(Question, on_delete=models.CASCADE)
    fid = models.ForeignKey(Fichier, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.qid) + " utilise le fichier " + str(self.fid)

qcmonge/webapp/qcmonge/models/general.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from qcmonge.models.classement import Matiere

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    matiere_preferee = models.ForeignKey(Matiere, on_delete=models.SET_NULL, null=True, verbose_name='matière préférée')

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

qcmonge/webapp/qcmonge/views/api.py
from django.http import JsonResponse, Http404
from django.conf import settings
from qcmonge.models.classement import Matiere, Theme, SousTheme
from qcmonge.models.question import Question

import json
import html


"""
Methodes qui retournent des json.
Elles ne sont pas destinées à être appelées par un humain mais par jquery en asynchrone.

Type d'entrée attendu : les données sont encapsulées dans un json qui se trouve
dans le champs 'jsondata' de la requête:
{ 'jsondata': "..." , ... }

Type de sortie attendu : On renvoi un json. Il contient obligatoirement l'attribut 'success'.
Si ce champs est à False, il s'est passé un truc pas normal et le serveur donne la raison dans l'attribut 'reason'.
Si ce champs est à True, les données sont dans l'attribut 'data':
{ 'success': False, 'reason': "..." }
{ 'success': True, 'data': "..." }
"""



def api_structure(request):
    if request.method == "GET":
        raise Http404("GET method not allowed")
    answer = {"success": False}
    data = {}
    nonempty = False
    validated = True
    try:
        postdata = json.loads(request.POST['jsondata'])
        if "nonempty_only" in postdata and postdata["nonempty_only"]:
            nonempty = postdata["nonempty_only"]
        if "even_non_validated" in postdata and postdata["even_non_validated"]:
            validated = False
    except:
        pass
    questions = Question.objects.filter(valide=True) if validated else Question.objects.all()
    matieres = Matiere.objects.all()
    for mat in matieres:
        okmat = (not nonempty) or len(questions.filter(thematique__theme__domaine=mat)) > 0
        if okmat:
            html_mat = html.escape(mat.intitule)
            data[html_mat] = {}
            themes = Theme.objects.filter(domaine=mat).order_by('sujet')
            for thm in themes:
                okthm = (not nonempty) or len(questions.filter(thematique__theme=thm)) > 0
                if okthm:
                    html_thm = html.escape(thm.sujet)
                    sousthemes = SousTheme.objects.filter(theme__domaine=mat, theme=thm).order_by('motcle')
                    data[html_mat][html_thm] = []
                    for sthm in sousthemes:
                        okssthm = (not nonempty) or len(questions.filter(thematique=sthm)) > 0
                        if okssthm:
                            data[html_mat][html_thm].append(html.escape(sthm.motcle))
    answer["data"] = data
    answer["success"] = True
    return JsonResponse(answer)


def api_search_questions(request):
    if request.method == "GET":
        raise Http404("GET method not allowed")
    answer = {"success": False}
    try:
        questions = Question.objects.filter( valide = True)
        postdata = json.loads(request.POST['jsondata'])
        mat = postdata['matiere']
        questions = questions.filter( thematique__theme__domaine = mat )
        thm = postdata['theme']
        questions = questions.filter( thematique__theme = thm )
        sthm = postdata['soustheme']
        questions = questions.filter( thematique = sthm )
        types = postdata['type']
        for t in "SMO":
            if t not in types:
                questions = questions.exclude( qtype = t )
        totquestion = len(questions)
        qlength = max(1, int(postdata['qlength'])) if 'qlength' in postdata else 5
        qoffset = max(0, int(postdata['qoffset'])) if 'qoffset' in postdata else 0
        if totquestion < qlength or qoffset > totquestion:
            qoffset = 0
        questions = questions.order_by('qid')[qoffset:qoffset+qlength]
        data = {}
        data["questions"] = [ { "id": q.qid, "enonce": q.enonce, "image": "/static/" + str(q.fichier_image) } for q in questions]
        data["offset"] = qoffset
        data["total"] = totquestion
        answer["success"] = True
        answer["data"] = data
    except KeyError as e:
        answer["reason"] = "The key " + str(e) + " is missing."
    except IndexError as e:
        answer["reason"] = str(e)
    return JsonResponse(answer)



def api_infos_questions(request):
    if request.method == "GET":
        raise Http404("GET method not allowed")
    answer = {"success": False}
    contexte = {}
    try:
        selected = json.loads(request.POST['jsondata'])
        selected = selected["questions"]
        for q in selected:
            quest = Question.objects.get(qid=q)
            contexte[q] = { "img": "/static/" + quest.fichier_image,
                            "enonce": quest.enonce}
        answer["data"] = contexte
        answer["success"] = True
    except Exception as e:
        answer["reason"] = "Error when finding question on server."
    return JsonResponse(answer)

qcmonge/webapp/qcmonge/views/exportation.py
from django.shortcuts import render
from django.http import HttpResponse, Http404

import json
from zipfile import ZipFile, ZIP_DEFLATED
from io import BytesIO

from qcmonge.models.question import Question

from qcmonge.forms.thematique import ThematiqueForm

from texanalizer.texanalyser import SynTexAnal
from texanalizer.texnodes import TexNode, TexTextNode
from texanalizer.textokenizer import TexToken
from texanalizer.texanalyseconstants import TexAnalyseConstants as TAC



"""
    Page de construction de QCM.
    
    On envoie les matières et les thèmes associés à la matière préférée.

    Les sélections et choix sont gérés par ajax (api_*).

"""
def export_qcm(request):
    mat_pref = "---"
    try:
        mat_pref = request.user.profile.matiere_preferee.intitule
    except:
        pass
    form = ThematiqueForm()
    contexte = {'matiere_preferee': mat_pref, 'form': form }
    return render(request, 'qcmonge/export_qcm.html', contexte)



"""
    téléchargement des questions
"""
def get_qcm_content(request):
    if request.method == "GET":
        raise Http404("GET method not allowed")
    try:
        selected = json.loads(request.POST['selected'])
        packages_header = TexNode()
        packages_names = {}
        commands_header = TexNode()
        commands_names = {}
        texcontent = ""
        for grp in selected.keys():
            for k in selected[grp]:
                quest = Question.objects.get(qid=k)
                head = SynTexAnal(quest.tex_header).latex_preambule_part
                cont = SynTexAnal(quest.enonce).latex_document_part
                added_packages = 0
                added_commands = 0
                for line in head:
                    if line.node_type == TAC.COMMAND_NODE and line.name == 'usepackage':
                        pacn = line.params[0].content
                        if pacn not in packages_names:
                            added_packages += 1
                            if added_packages == 1:
                                packages_header.append(TexTextNode(TexToken(TAC.COMMENT_TOKEN, "% packages for question " + str(k) + "\n")))
                            packages_header.append(line)
                            packages_names[pacn] = line
                        else:
                            my_package = line.rebuild_latex(with_comments=False, after_content=False)
                            their_package = packages_names[pacn].rebuild_latex(with_comments=False, after_content=False)
                            if my_package != their_package:
                                added_packages += 1
                                if added_packages == 1:
                                    packages_header.append(TexTextNode(TexToken(TAC.COMMENT_TOKEN, "% packages for question " + str(k) + "\n")))
                                packages_header.append(TexTextNode(TexToken(TAC.COMMENT_TOKEN,"% " + line.rebuild_latex() + "\n")))
                    elif line.node_type & (TAC.NEW_MASK + TAC.RENEW_MASK) > 0:
                        if line.name not in commands_names:
                            added_commands += 1
                            if added_commands == 1:
                                commands_header.append(TexTextNode(TexToken(TAC.COMMENT_TOKEN, "% commands for question " + str(k) + "\n")))
                            commands_header.append(line)
                        else:
                            my_command = line.rebuild_latex(with_comments=False, after_content=False)
                            their_command = commands_names[line.name]
                            if my_command != their_command:
                                newname = _newname(line.name, commands_names)
                                head.modifyCmdEnvName(line.name, newname, line.node_type)
                                cont.modifyCmdEnvName(line.name, newname, line.node_type)
                                nt = (line.node_type & (TAC.NEW_MASK+TAC.RENEW_MASK)) | TAC.SIMPLE_MASK
                                head.modifyCmdEnvName(line.name, newname, nt)
                                cont.modifyCmdEnvName(line.name, newname, nt)
                                added_commands += 1
                                if added_commands == 1:
                                    commands_header.append(TexTextNode(TexToken(TAC.COMMENT_TOKEN, "% commands for question " + str(k) + "\n")))
                                commands_header.append(line)
                        commands_names[line.name] = line.rebuild_latex(with_comments=False, after_content=False)
                if added_packages > 0:
                    packages_header.append(TexTextNode(TexToken(TAC.COMMENT_TOKEN, "\n\n")))
                if added_commands > 0:
                    commands_header.append(TexTextNode(TexToken(TAC.COMMENT_TOKEN, "\n\n")))
                texcontent += _englob_question(grp, k, cont.rebuild_latex(), quest.qtype)
        texheader = packages_header.rebuild_latex() + "\n\n" +  commands_header.rebuild_latex()

        mem_zip = BytesIO()
        with ZipFile(mem_zip, mode="w", compression=ZIP_DEFLATED) as zf:
            zf.writestr("header.tex", texheader)
            zf.writestr("content.tex", texcontent)
        response = HttpResponse(mem_zip.getvalue(), content_type='application/zip')
        response['Content-Disposition'] = 'attachment; filename="qcm-amc.zip"'
        return response
    except KeyError as e:
        contexte = {
            "errmsg": "Error when generating zip file: The key " + str(e) + " is missing.",
            "matiere_preferee": matiere_preferee(request),
        }
    return render(request, 'qcmonge/export_qcm.html', contexte)



"""
Ceci n'est pas une vue. C'est une fonction annexe.
Elle pernet de trouver un nom d'une commande LaTeX qui n'est 
pas encore pris parmis les commandes déjà disponibles.
"""
def _newname(cmd, cmds):
    n, s = 0, "A"
    while cmd + s in cmds:
        n += 1
        s, p = "", n
        while p > 0:
            s += chr(65+(p%26))
            p = p//26
    return cmd + s

def _englob_question(group_name, qid, content, qtype):
    mult = "mult" if qtype == "M" else ""
    prefix = "" if len(group_name) == 0 else "\\element{" + group_name + "}{\n"
    suffix = "" if len(group_name) == 0 else "\n}"
    return "\n" + prefix + "\\begin{question" + mult + "}{" + str(qid) + "}\n" + content + "\n\\end{question" + mult + "}" + suffix + "\n"

qcmonge/webapp/qcmonge/views/general.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from qcmonge.models.classement import Matiere, Theme, SousTheme
from qcmonge.models.question import Question
from django.contrib.auth.models import User


"""
    Page par defaut.

    On affiche juste la liste des utilisateurs.

    /!\ A modifier /!\
"""
def index(request):
    return render(request, 'qcmonge/index.html', {'users': User.objects.all()})




"""
    Page de profile d'un utilisateur.

    Vide (ou presque) pour l'instant.
"""
def voir_user(request, user_login):
    user = get_object_or_404(User, username=user_login)
    return HttpResponse("Module de visualisation de l'utilisateur " + user.username)



"""
    Page de visualisation des themes.

    Vide (ou presque) pour l'instant.
"""
def voir_themes(request):
    mtsq = {}
    mats = Matiere.objects.all()
    for m in mats:
        mtsq[m] = {}
        thms = Theme.objects.filter(domaine=m)
        for t in thms:
            mtsq[m][t] = {}
            sthms = SousTheme.objects.filter(theme=t)
            for s in sthms:
                qt = Question.objects.filter(thematique=s)
                qv = qt.filter(valide=True)
                mtsq[m][t][s] = str(len(qv)) + " / " + str(len(qt))
    contexte = {'matieres': mtsq}
    return render(request, 'qcmonge/voir_themes.html', contexte)

qcmonge/webapp/qcmonge/templates/qcmonge/change-pwd-done.html
{% extends 'base.html' %}
{% load static %}

{% block titre %}mot de passe mis à jour- QCMONGE{% endblock %}
{% block entete %}
<h1>Changement de votre mot de passe</h1>
{% endblock %}


{% block contenu %}
{% if form.errors %}
<p>Erreurs.</p>
{% endif %}

{% if user.is_authenticated %}
<p>Votre mot de passe a été modifié.</p>
{% else %}
<p>Vous devez être connecté.</p>
{% endif %}

{% endblock %}

qcmonge/webapp/qcmonge/templates/qcmonge/export_qcm.html
{% extends 'base.html' %}
{% load static %}

{% block titre %}export QCM - QCMONGE{% endblock %}
{% block entete %}
<h1 id="titre">Construction de votre QCM</h1>
{% endblock %}

{% block contenu %}
<form method="post" action="{% url 'get-qcm-content' %}" onsubmit='QCMONGE.prepare_qcm()'>
  {% csrf_token %}
  <div id="selection">
    <div id="liste-themes" class="module">
      <table>
        <caption>Sélection du sujet</caption>
        <tbody>
          <tr>
            <th>{{ form.matiere.label_tag }} {{ form.matiere }}</th>
            <th>{{ form.theme.label_tag }} {{ form.theme }}</th>
            <th>{{ form.soustheme.label_tag }} {{ form.soustheme }}</th>
          </tr>
        </tbody>
      </table>
    </div>
    <div id="type-question" class="module">
      <table>
        <caption>Type de questions</caption>
        <tbody>
          <tr>
            <th><input type="checkbox" name="simple" id="simpleQ" checked onchange='QCMONGE.update_questions(0)'/>
              <label for="simpleQ">Une seule bonne réponse</label></th>
            <th><input type="checkbox" name="multi" id="multiQ" class="a_droite" checked onchange='QCMONGE.update_questions(0)'/>
              <label for="multiQ">Plusieurs bonnes réponses possibles</label></th>
            <th><input type="checkbox" name="ouvert" id="ouvertQ" class="a_droite" checked onchange='QCMONGE.update_questions(0)'/>
              <label for="ouvertQ">Question ouverte</label></th>
          </tr>
        </tbody>
      </table>
    </div>
    <div id="nb-question">
      <span id="totquestion">0</span> questions correspondent à vos critères.
      <span class="a_droite">Afficher <select id="nbquestion" name="nbquestion" onchange='QCMONGE.update_questions(0)'>
        <option>5
        <option>10
        <option>25
        <option>50
      </select> questions par page.</span>
    </div>
    <table style="width: 100%;">
      <tbody>
        <tr>
          <td class="module" style="vertical-align: top; width: 50%">
              <table>
                <caption>Questions suggérées</caption>
                <tbody>
                  <td id="liste-questions"></td>
                </tbody>
              </table>
          </td>
          <td class="module" style="vertical-align: top; width: 50%">
              <table>
                <caption>Questions sélectionnées</caption>
                <tbody>
                  <td id="selected-questions"></td>
                </tbody>
              </table>
          </td>
        </tr>
      </tbody>
    </table>
    
    <div id="boutons">
      <input type="hidden" id="id_matiere_preferee" value="{{ matiere_preferee }}">
      <input type="hidden" id="qoffset" name="qoffset" value="0" />
      <input type="button" id="prevbut" name="prev-button" value="Questions précédentes" disabled="true" onclick='QCMONGE.update_questions(-1)' />
      <input type="button" id="nextbut" name="next-button" value="Questions suivantes" disabled="true" onclick='QCMONGE.update_questions(1)' />
      <input type="button" id="allbut" name="all-button" class="a_droite" value="Sélectionner toutes les questions" disabled="true" onclick='QCMONGE.select_all_questions()' />
      <input type="button" id="razbut" name="raz-button" value="Effacer toute la sélection"  disabled="true" onclick='QCMONGE.unselect_all_questions()' />
      <input type="button" id="viewbut" name="view-button" class="a_droite" value="Voir mon QCM" disabled="true" onclick='QCMONGE.show_groups()' />
    </div>
  </div>

  <div id="groupement" class="passive_tab">
    <p> Voici les questions que vous avez sélectionnées pour votre QCM.</p>
    <p> Si cela ne vous convient pas, vous pouvez encore désélectionner quelques questions.
      Pour en ajouter, veuillez revenir à la sélection.</p>
    <p> Si cela vous convient, cliquez sur le bouton de téléchargement en bas.
      Notez que les fichiers obtenus ne sont pas viables seuls. Il ne contient que les questions
      que vous avez choisies et les directives essentielles pour les compiler (les packages et les commandes).
      Il vous manque toute la présentation (préambule LaTeX, mise en forme,...). </p>
    <p> Le plus simple pour vous est d'avoir un fichier tex contenant votre préambule
      (tous vos <span class="dutex">\usepackage</span>) et la présentation
      (le <span class="dutex">\exemplaire</span>),
      appelé par exemple <span class="desnomsfichiers">mon-qcm.tex</span>.
      Dézipez le fichier téléchargé et placez son contenu (<span class="desnomsfichiers">header.tex</span>
      et <span class="desnomsfichiers">content.tex</span>) dans le même répertoire.
      
      Éditez <span class="desnomsfichiers">mon-qcm.tex</span> pour ajouter les commandes suivantes
      <ul>
        <li><span class="dutex"> \input{header}</span> entre préambule et le <span class="dutex">\begin{document}</span></li>
        <li><span class="dutex"> \input{content}</span> entre le <span class="dutex">\begin{document}</span> et
          le <span class="dutex">\exemplaire</span></li>
      </ul>
    </p>
    <hr />
    
    <p>Vous avez ici la possibilité d'organiser vos questions en groupe.
      Dans ce cas, vos questions sont mélangées à l'intérieur d'un groupe ce qui fait que
      les questions d'un même sujet restent regroupées.</p>
    
    <table style="width: 100%;">
      <tbody>
        <tr>
          <td id="groupless"></td>
          <td id="group-container"></td>
        </tr>
      </tbody>
    </table>
    
    <div id="poubelle">
      Glisser ici pour supprimer une question
    </div>
    
    <div id="boutons">
      <input type="hidden" id="selected" name="selected" value="" />
      <input type="button" id="goback-button" name="go-back" value="Revenir à la sélection" onclick='QCMONGE.show_selection()' />
      <input type="button" id="grpbut" name="group-button" class="a_droite" value="ajouter un groupe" onclick='QCMONGE.add_group()' />
      <input type="submit" id="getbut" name="get-button" class="a_droite" value="Télécharger les questions" />
    </div>
    
  </div>
</form>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/thematique.js' %}"></script>
<script src="{% static 'js/export.js' %}"></script>
{% endblock %}

qcmonge/webapp/qcmonge/templates/qcmonge/import1_qcm.html
{% extends 'base.html' %}
{% load static %}

{% block titre %}import QCM - QCMONGE{% endblock %}
{% block entete %}
<h1>Importation de votre QCM</h1>
{% endblock %}

{% block contenu %}
<form method="post" action="{% url 'import1-qcm' %}" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="hidden" id="id_matiere_preferee" value="{{ matiere_preferee }}">
  <p>
    Pour renseigner les matières/thèmes/sous-thèmes des questions que vous aller importer, vous avez plusieurs solutions:
    <ul>
      <li>Si toutes les questions portent sur le même sous-thème, vous pouvez pré-remplir les informations maintenant.</li>
      <li>Vous pouvez les renseigner dans le fichier LaTeX avec les balises <span class="balise">%%-QCMONGE-MATIERE:</span>,
        <span class="balise">%%-QCMONGE-THEME:</span> et <span class="balise">%%-QCMONGE-SOUS-THEME:</span>.</li>
      <li>Sinon, il vous faudra les remplir une par une pour toutes les questions trouvées dans la page suivante.</li>
    </ul>
  </p>
  
  <table>
    {{ form.as_table }}
  </table>
  <div id="boutons">
    <input type="submit" id="uploadbut" name="upload-button" value="Téléverser le QCM" />
  </div>
</form>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/thematique.js' %}"></script>
<script src="{% static 'js/import.js' %}"></script>
{% endblock %}

qcmonge/webapp/qcmonge/templates/qcmonge/import2_qcm.html
{% extends 'base.html' %}
{% load static %}

{% block titre %}valide QCM - QCMONGE{% endblock %}
{% block entete %}
<h1>Validation de l'import de votre QCM</h1>
{% endblock %}

{% block contenu %}
<p>
  Veuillez vérifier les données trouvées par QCMonge et compléter si nécessaire.
  Chaque question valide sera enregistrée de manière définitive dans la base.
  Elle ne pourra alors plus être modifiée.
</p>
<p>
  Si vous constatez qu'il manque des questions par rapport à votre fichier initial, ceci peut signifier deux choses:
  <ul>
    <li>QCMonge n'a pas réussi à trouver votre question.</li>
    <li>QCMonge n'a pas réussi à compiler votre question. </li>
  </ul>
  Dans ce cas, il est possible que la syntaxe de votre question soit un peu trop exotique pour QCMonge.
</p>
<p>
  Vous avez la possibilité de modifier le préambule et la version LaTeX de chaque question.
  Si au moins une de ces données est modifiée, la question ne sera pas validée complètement:
  QCMonge vérifiera d'abord qu'il peut compiler la question et vous proposera à nouveau de valider vos modifications.
</p>
<form method="post" action="#" id="qlistform" >
  {% csrf_token %}
  {% for formul, image, enonce, nom in form_img_tex_nom %}
  <fieldset id="id_{{ nom }}" class="single_quest">
    <div style="width: 100%">{{ formul.non_field_errors }}</div>
    <table style="width: 100%;">
      <tbody>
        <tr>
          <th>{{ formul.matiere.label_tag }} {{ formul.matiere }}</th>
          <th>{{ formul.theme.label_tag }} {{ formul.theme }}</th>
          <th>{{ formul.soustheme.label_tag }} {{ formul.soustheme }}</th>
        </tr>
      </tbody>
    </table>
    <table style="width: 100%;">
      <tbody>
        <tr>
          <th>{{ formul.keepme.label_tag }} {{ formul.keepme }}</th>
          <th>{{ formul.qtype.label_tag }} {{ formul.qtype }}</th>
        </tr>
      </tbody>
    </table>
    <table style="width: 100%;">
      <tbody>
        <tr>
          <th class="header_content">
            {{ formul.texheader.label_tag }}
            {{ formul.texheader }}
            {{ formul.texcontent.label_tag }}
            {{ formul.texcontent }}
          </th>
          <td style="width: 50%;">
            <img src="{% static image %}" alt="{{ enonce }}" style="width: 100%">
          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
  {% endfor %}
  
  <div id="boutons">
    <input type="hidden" id="qids" name="qids" value="{{ qids }}">
    <input type="hidden" id="id_matiere_preferee" value="{{ matiere_preferee }}">
    <input type="submit" value="Valider les questions" />
  </div>
</form>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/thematique.js' %}"></script>
<script src="{% static 'js/final-import.js' %}"></script>
{% endblock %}